//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiota.Resources.Localizations {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Chiota.Resources.Localizations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CmnBackUp {
            get {
                return ResourceManager.GetString("CmnBackUp", resourceCulture);
            }
        }
        
        internal static string CmnInvoices {
            get {
                return ResourceManager.GetString("CmnInvoices", resourceCulture);
            }
        }
        
        internal static string CmnConfirmSeed {
            get {
                return ResourceManager.GetString("CmnConfirmSeed", resourceCulture);
            }
        }
        
        internal static string CmnContacts {
            get {
                return ResourceManager.GetString("CmnContacts", resourceCulture);
            }
        }
        
        internal static string CmnHelp {
            get {
                return ResourceManager.GetString("CmnHelp", resourceCulture);
            }
        }
        
        internal static string CmnLogOut {
            get {
                return ResourceManager.GetString("CmnLogOut", resourceCulture);
            }
        }
        
        internal static string CmnNewSeed {
            get {
                return ResourceManager.GetString("CmnNewSeed", resourceCulture);
            }
        }
        
        internal static string CmnPrintPaperCopy {
            get {
                return ResourceManager.GetString("CmnPrintPaperCopy", resourceCulture);
            }
        }
        
        internal static string CmnPrivacyPolicy {
            get {
                return ResourceManager.GetString("CmnPrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string CmnProfile {
            get {
                return ResourceManager.GetString("CmnProfile", resourceCulture);
            }
        }
        
        internal static string CmnQrCode {
            get {
                return ResourceManager.GetString("CmnQrCode", resourceCulture);
            }
        }
        
        internal static string CmnSetPassword {
            get {
                return ResourceManager.GetString("CmnSetPassword", resourceCulture);
            }
        }
        
        internal static string CmnSetSeed {
            get {
                return ResourceManager.GetString("CmnSetSeed", resourceCulture);
            }
        }
        
        internal static string CmnSettings {
            get {
                return ResourceManager.GetString("CmnSettings", resourceCulture);
            }
        }
        
        internal static string CmnSetUser {
            get {
                return ResourceManager.GetString("CmnSetUser", resourceCulture);
            }
        }
        
        internal static string CmnWriteSeedDown {
            get {
                return ResourceManager.GetString("CmnWriteSeedDown", resourceCulture);
            }
        }
        
        internal static string DlgCancel {
            get {
                return ResourceManager.GetString("DlgCancel", resourceCulture);
            }
        }
        
        internal static string DlgContinue {
            get {
                return ResourceManager.GetString("DlgContinue", resourceCulture);
            }
        }
        
        internal static string DlgDescBackUp {
            get {
                return ResourceManager.GetString("DlgDescBackUp", resourceCulture);
            }
        }
        
        internal static string DlgDescConfirmSeed {
            get {
                return ResourceManager.GetString("DlgDescConfirmSeed", resourceCulture);
            }
        }
        
        internal static string DlgDescLogIn {
            get {
                return ResourceManager.GetString("DlgDescLogIn", resourceCulture);
            }
        }
        
        internal static string DlgDescNewSeed {
            get {
                return ResourceManager.GetString("DlgDescNewSeed", resourceCulture);
            }
        }
        
        internal static string DlgDescPrintPaperCopy {
            get {
                return ResourceManager.GetString("DlgDescPrintPaperCopy", resourceCulture);
            }
        }
        
        internal static string DlgDescQrCode {
            get {
                return ResourceManager.GetString("DlgDescQrCode", resourceCulture);
            }
        }
        
        internal static string DlgDescSeedView {
            get {
                return ResourceManager.GetString("DlgDescSeedView", resourceCulture);
            }
        }
        
        internal static string DlgDescSetPassword {
            get {
                return ResourceManager.GetString("DlgDescSetPassword", resourceCulture);
            }
        }
        
        internal static string DlgDescSetSeed {
            get {
                return ResourceManager.GetString("DlgDescSetSeed", resourceCulture);
            }
        }
        
        internal static string DlgDescSetUser {
            get {
                return ResourceManager.GetString("DlgDescSetUser", resourceCulture);
            }
        }
        
        internal static string DlgDescWelcome {
            get {
                return ResourceManager.GetString("DlgDescWelcome", resourceCulture);
            }
        }
        
        internal static string DlgDescWriteSeedDown {
            get {
                return ResourceManager.GetString("DlgDescWriteSeedDown", resourceCulture);
            }
        }
        
        internal static string DlgGenerateSeed {
            get {
                return ResourceManager.GetString("DlgGenerateSeed", resourceCulture);
            }
        }
        
        internal static string DlgGotIt {
            get {
                return ResourceManager.GetString("DlgGotIt", resourceCulture);
            }
        }
        
        internal static string DlgHelpSeed {
            get {
                return ResourceManager.GetString("DlgHelpSeed", resourceCulture);
            }
        }
        
        internal static string DlgHelpSeedDesc0 {
            get {
                return ResourceManager.GetString("DlgHelpSeedDesc0", resourceCulture);
            }
        }
        
        internal static string DlgHelpSeedDesc1 {
            get {
                return ResourceManager.GetString("DlgHelpSeedDesc1", resourceCulture);
            }
        }
        
        internal static string DlgHelpSeedDesc2 {
            get {
                return ResourceManager.GetString("DlgHelpSeedDesc2", resourceCulture);
            }
        }
        
        internal static string DlgLeastSecure {
            get {
                return ResourceManager.GetString("DlgLeastSecure", resourceCulture);
            }
        }
        
        internal static string DlgLogIn {
            get {
                return ResourceManager.GetString("DlgLogIn", resourceCulture);
            }
        }
        
        internal static string DlgMostSecure {
            get {
                return ResourceManager.GetString("DlgMostSecure", resourceCulture);
            }
        }
        
        internal static string DlgName {
            get {
                return ResourceManager.GetString("DlgName", resourceCulture);
            }
        }
        
        internal static string DlgNewSeed {
            get {
                return ResourceManager.GetString("DlgNewSeed", resourceCulture);
            }
        }
        
        internal static string DlgOk {
            get {
                return ResourceManager.GetString("DlgOk", resourceCulture);
            }
        }
        
        internal static string DlgPassword {
            get {
                return ResourceManager.GetString("DlgPassword", resourceCulture);
            }
        }
        
        internal static string DlgRepeatPassword {
            get {
                return ResourceManager.GetString("DlgRepeatPassword", resourceCulture);
            }
        }
        
        internal static string DlgSaveQrCode {
            get {
                return ResourceManager.GetString("DlgSaveQrCode", resourceCulture);
            }
        }
        
        internal static string DlgScanQrCode {
            get {
                return ResourceManager.GetString("DlgScanQrCode", resourceCulture);
            }
        }
        
        internal static string DlgSeed {
            get {
                return ResourceManager.GetString("DlgSeed", resourceCulture);
            }
        }
        
        internal static string DlgSetSeed {
            get {
                return ResourceManager.GetString("DlgSetSeed", resourceCulture);
            }
        }
        
        internal static string DlgWriteSeedDown {
            get {
                return ResourceManager.GetString("DlgWriteSeedDown", resourceCulture);
            }
        }
        
        internal static string CmnAddContact {
            get {
                return ResourceManager.GetString("CmnAddContact", resourceCulture);
            }
        }
        
        internal static string CmnContactAddress {
            get {
                return ResourceManager.GetString("CmnContactAddress", resourceCulture);
            }
        }
        
        internal static string DlgHelpContactAddress {
            get {
                return ResourceManager.GetString("DlgHelpContactAddress", resourceCulture);
            }
        }
        
        internal static string DlgSave {
            get {
                return ResourceManager.GetString("DlgSave", resourceCulture);
            }
        }
        
        internal static string CmnEdit {
            get {
                return ResourceManager.GetString("CmnEdit", resourceCulture);
            }
        }
        
        internal static string CmnAbout {
            get {
                return ResourceManager.GetString("CmnAbout", resourceCulture);
            }
        }
        
        internal static string DlgAccept {
            get {
                return ResourceManager.GetString("DlgAccept", resourceCulture);
            }
        }
        
        internal static string DlgDecline {
            get {
                return ResourceManager.GetString("DlgDecline", resourceCulture);
            }
        }
        
        internal static string CmnContactRequest {
            get {
                return ResourceManager.GetString("CmnContactRequest", resourceCulture);
            }
        }
        
        internal static string DlgMessage {
            get {
                return ResourceManager.GetString("DlgMessage", resourceCulture);
            }
        }
        
        internal static string DlgSettingUpAccount {
            get {
                return ResourceManager.GetString("DlgSettingUpAccount", resourceCulture);
            }
        }
        
        internal static string DlgLoggingIn {
            get {
                return ResourceManager.GetString("DlgLoggingIn", resourceCulture);
            }
        }
        
        internal static string DlgAddContact {
            get {
                return ResourceManager.GetString("DlgAddContact", resourceCulture);
            }
        }
        
        internal static string CmnSearch {
            get {
                return ResourceManager.GetString("CmnSearch", resourceCulture);
            }
        }
        
        internal static string CmnNewContact {
            get {
                return ResourceManager.GetString("CmnNewContact", resourceCulture);
            }
        }
    }
}
